services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    #image: phpmyadmin:5.2.0-apache
    hostname: dockercompose-frontend
    #container_name: phpmyadmin
    ports:

      - "80:80"
    environment:
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: admin
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_HOST: mydb

      #PMA_USER: user
      #PMA_PASSWORD: userpassword

    # networks:
    #   - frontend
    depends_on:
      - mydb
    #    condition: service_healthy
  mydb:
    build:
      context: .
      dockerfile: Dockerfiledb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    hostname: mydb
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 15s
      retries: 5
    # networks:
    #   - frontend


# networks:
#   frontend:
#     name: dockercompose-frontend
#     labels:
#       - "network=Custom"
volumes:
  db-data:
