services:

  filegator:
    container_name: filegator
    image: filegator/filegator
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # common mount points are listed here
      # make sure filegator can read/write to the mounted volume

      # mount local folder as a repository
      - ./www/wp-content:/var/www/filegator/repository

  phpmyadm:
    build:
      context: .
      dockerfile: Dockerfilepm
    #image: phpmyadmin:5.2.0-apache
    hostname: dockercompose-frontend
    #container_name: phpmyadmin
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mydb
      #PMA_USER: user
      #PMA_PASSWORD: userpassword


    depends_on:
      - mydb


  init-wp:
      image: wordpress-frontend:latest
      command: wp config create
      environment:
        WORDPRESS_USERNAME: admin
        WORDPRESS_PASSWORD: admin
        WORDPRESS_DATABASE_USER: wordpress
        WORDPRESS_DATABASE_PASSWORD: wordpress
        WORDPRESS_DATABASE_NAME: wordpress
        WORDPRESS_DATABASE_HOST: mydb
      volumes:
        - ./www:/bitnami/wordpress

          depends_on:
            - mydb


                # condition: service_started


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    #image: phpmyadmin:5.2.0-apache
    hostname: dockercompose-frontend
    #container_name: phpmyadmin
    ports:

      - "80:8080"
      - "443:8443"
    environment:
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: admin
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_HOST: mydb
    #  WORDPRESS_MULTISITE_FILEUPLOAD_MAXK:  281920

      #PMA_USER: user
      #PMA_PASSWORD: userpassword
    volumes:
      - ./www:/bitnami/wordpress

    depends_on:
      - mydb
    #    condition: service_healthy

  mydb:
    build:
      context: .
      dockerfile: Dockerfiledb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    hostname: mydb
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 15s
      retries: 5
